name: Model Pipeline

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download model artifact
        uses: actions/download-artifact@v2
        with:
          name: model
          path: GenZ-checkpoints
