name: Model Pipeline

on:
  workflow_run:
    workflows: ["Train Model"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download model artifact
        uses: actions/download-artifact@v2
        with:
          name: model
          path: GenZ-checkpoints

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build documentation
        run: mkdocs build

      - name: Check links
        run: |
          pip install linkchecker
          linkchecker ./site/
